# Codecov configuration for templ-pipeline
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%  # Allow 1% coverage decrease
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        
  ignore:
    - "tests/"
    - "scripts/"
    - "deploy/"
    - "benchmarks/"
    - "data/"
    - "output/"
    - "temp/"
    - "tools/"
    - "**/__pycache__/"
    - "**/*.pyc"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false