[tool.deptry]
# Ignore self-imports and dev dependencies
ignore_transitive = ["templ_pipeline"]
ignore_obsolete = ["pytest", "pytest-cov", "black", "isort", "flake8", "mypy"]

# Root of the project
src = ["."]

# Files/directories to exclude from scanning
exclude = [
    ".git",
    ".pytest_cache", 
    "__pycache__",
    "*.egg-info",
    "htmlcov",
    "tests",
    "ui/archive",
]

# Don't check for these types of issues
skip_obsolete = false
skip_missing = false
skip_transitive = true 