apiVersion: apps/v1
kind: Deployment
metadata:
  name: templ-pipeline
  labels:
    app: templ-pipeline
    version: production
    component: application
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: templ-pipeline
  template:
    metadata:
      labels:
        app: templ-pipeline
        version: production
        component: application
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - templ-pipeline
              topologyKey: kubernetes.io/hostname
      
      containers:
      - name: templ-pipeline
        image: cerit.io/xfulop/templ-pipeline@sha256:a3c3a7f3aaf5a3beb3d319eda36df72172640fc7bddaa62f710454e94c2e323d
        imagePullPolicy: Always
        
        command: ["/bin/bash", "-c"]
        args: 
        - |
          echo "Starting TEMPL Pipeline..."
          
          # Create necessary directories
          mkdir -p /app/data/embeddings /app/data/ligands /app/temp
          
          # Initialize code storage if empty
          if [ ! "$(ls -A /code/templ_pipeline)" ]; then
            echo "Initializing code storage..."
            mkdir -p /code/templ_pipeline /code/scripts
            cp -r /app/templ_pipeline/* /code/templ_pipeline/
            cp -r /app/scripts/* /code/scripts/ 2>/dev/null || true
            chown -R 1000:1000 /code
            echo "Code storage initialized"
          else
            echo "Code storage already exists"
          fi
          
          # Copy latest code from persistent storage to app directory (without rsync)
          echo "Syncing code from persistent storage..."
          rm -rf /app/templ_pipeline/*
          cp -a /code/templ_pipeline/. /app/templ_pipeline/
          if [ -d "/code/scripts" ]; then
            mkdir -p /app/scripts
            rm -rf /app/scripts/*
            cp -a /code/scripts/. /app/scripts/
          fi
          
          # Set proper permissions
          chown -R 1000:1000 /app/templ_pipeline /app/scripts
          
          echo "Starting Streamlit application..."
          exec /opt/conda/envs/templ/bin/streamlit run /app/templ_pipeline/ui/app.py \
            --server.headless=true \
            --server.port=8501 \
            --server.address=0.0.0.0 \
            --server.fileWatcherType=poll \
            --server.runOnSave=true
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          runAsUser: 1000
          runAsNonRoot: true
        
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TEMPL_PASSWORD_HASH
          value: "b4c79b6941f774ee2fce7e15b454f151b20b926c0c174761346ff19c86fd59bd"
        - name: TEMPL_ENV
          value: "production"
        - name: TEMPL_N_WORKERS
          value: "4"
        - name: TEMPL_N_CONFS
          value: "150"
        - name: TEMPL_SIM_THRESHOLD
          value: "0.5"
        - name: TEMPL_USE_CACHE
          value: "true"
        - name: TEMPL_ENABLE_BATCHING
          value: "true"
        - name: TEMPL_MAX_BATCH_SIZE
          value: "16"
        - name: OMP_NUM_THREADS
          value: "4"
        - name: TORCH_HOME
          value: "/app/data/.torch"
        - name: TEMPL_SKIP_DATA_DOWNLOAD
          value: "false"
        - name: TEMPL_ENABLE_EMBEDDINGS
          value: "true"
        - name: TEMPL_ENABLE_FULL_FEATURES
          value: "true"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: "/tmp/nvidia-mps"
        - name: CUDA_MPS_LOG_DIRECTORY
          value: "/tmp/nvidia-log"
        - name: LD_LIBRARY_PATH
          value: "/usr/lib/x86_64-linux-gnu"
        - name: QT_X11_NO_MITSHM
          value: "1"
        
        envFrom:
        - configMapRef:
            name: templ-pipeline-config
        
        ports:
        - containerPort: 8501
          name: http
          protocol: TCP
        
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
          readOnly: false
        - mountPath: /app/temp
          name: temp-volume
        - mountPath: /code
          name: code-volume
        
        resources:
          requests:
            memory: "12Gi"
            cpu: "8"
            nvidia.com/mig-1g.10gb: 1
            ephemeral-storage: "20Gi"
          limits:
            memory: "20Gi"
            cpu: "12"
            nvidia.com/mig-1g.10gb: 1
            ephemeral-storage: "20Gi"
        
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: templ-data-pvc
      - name: temp-volume
        emptyDir:
          sizeLimit: 16Gi
      - name: code-volume
        persistentVolumeClaim:
          claimName: templ-code-pvc
      
      nodeSelector:
        kubernetes.io/os: linux
        # Optional: request a specific GPU type if needed per CERIT docs
        # nvidia.com/gpu.product: 'NVIDIA-A40'
      
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "2"
        - name: edns0 