apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: templ-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Adjust based on your data size
  storageClassName: nfs-csi
