# TEMPL Pipeline Kubernetes Secrets Template
# 
# This file shows the structure of required secrets.
# DO NOT commit actual secret values to git.
# 
# To use:
# 1. Copy this file to secrets.yaml
# 2. Replace placeholder values with actual base64-encoded secrets
# 3. Apply with: kubectl apply -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: templ-pipeline-secrets
  namespace: default
  labels:
    app: templ-pipeline
    component: secrets
type: Opaque
data:
  # TEMPL Pipeline authentication hash
  # Generate with: echo -n "$(echo -n 'your_password' | sha256sum | cut -d' ' -f1)" | base64
  TEMPL_PASSWORD_HASH: "REPLACE_WITH_BASE64_ENCODED_PASSWORD_HASH"
  
  # Streamlit cookie secret for session security
  # Generate with: echo -n "$(openssl rand -hex 32)" | base64
  STREAMLIT_SERVER_COOKIE_SECRET: "REPLACE_WITH_BASE64_ENCODED_COOKIE_SECRET"

---
apiVersion: v1
kind: Secret
metadata:
  name: templ-basic-auth
  namespace: default
  labels:
    app: templ-pipeline
    component: ingress-auth
type: Opaque
data:
  # HTTP Basic Auth for ingress (optional)
  # Generate with: htpasswd -nb username password | base64 -w 0
  auth: "REPLACE_WITH_BASE64_ENCODED_HTPASSWD_ENTRY"

---
# Example of using the generate-auth.sh script:
#
# ./deploy/scripts/generate-auth.sh \
#   --app-password "your_secure_password" \
#   --ingress-user "admin" \
#   --ingress-password "ingress_password" \
#   --namespace "default"
#
# This will output the YAML snippets needed to fill in the placeholders above.