[global]
# Disable file watching for PyTorch and related modules to prevent conflicts
# with dynamic class loading systems
showWarningOnDirectExecution = false

[server]
# Disable file watcher for problematic modules
fileWatcherType = "none"
runOnSave = false

[logger]
# Reduce log verbosity to avoid module inspection warnings
level = "error"

[browser]
# Optional: Improve browser compatibility
gatherUsageStats = false 